Areas/MCMS/Controllers/LogoController.cs
using Microsoft.AspNetCore.Mvc;
using MitechCenter.vn.Models.Repository;
using MitechCenter.vn.Models;
using MitechCenter.vn.statics;
using System;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace MitechCenter.vn.Areas.MCMS.Controllers
{
    [Area("MCMS")]
    [Authorize(Roles = "0")]
    public class LogoController : Controller
    {
        private readonly IDataRepository<StaticElement> _context;
        public LogoController(IDataRepository<StaticElement> context)
        {
            this._context = context;
        }
        public IActionResult Index()
        {
            ViewBag.notification = "";
            StaticElement staticElement = _context.Get(StaticElementKey.LOGO);
            return View(staticElement);
        }

        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile logo)
        {
            if (logo.Length > 0)
            {
                string newPath = "/landing/img/logo_" + Stopwatch.GetTimestamp() + ".png";
                using (var fs = new FileStream("./wwwroot/" + newPath, FileMode.Create))
                {
                    await logo.CopyToAsync(fs);
                    StaticElement staticElement = _context.Get(StaticElementKey.LOGO);
                    StaticElement _temp = new StaticElement();
                    _temp.DeepCopy(staticElement);
                    _temp.eData = newPath;
                    _context.Update(staticElement, _temp);
                }
            }
            return RedirectToAction("Index");
        }
    }
}

Areas/MCMS/Views/Logo/Index.cshtml
@using MitechCenter.vn.Models;
@model StaticElement
@{
	ViewData["Title"] = "LOGO";
}
<!-- ============================================================== -->
<!-- Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<div class="page-breadcrumb">
	<div class="row">
		<div class="col-7 align-self-center">
			<h4 class="page-title text-truncate text-dark font-weight-medium mb-1">Ảnh thương hiệu</h4>
			<div class="d-flex align-items-center">
				<nav aria-label="breadcrumb">
					<ol class="breadcrumb m-0 p-0">
						<li class="breadcrumb-item"><a href="index.html" class="text-muted">MCMS</a></li>
						<li class="breadcrumb-item text-muted active" aria-current="page">Trang chủ</li>
					</ol>
				</nav>
			</div>
		</div>
	</div>
</div>
<!-- ============================================================== -->
<!-- End Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->

 <!-- ============================================================== -->
<!-- Container fluid  -->
<!-- ============================================================== -->
<div class="container-fluid">
	<!-- ============================================================== -->
	<!-- Start Page Content -->
	<!-- ============================================================== -->
	<div class="card">
		<div class="card-body">
			<div class="text-center">
				<img src="@Model.eData" style="max-width: 200px; max-height: 200px;"/>
			</div>
			<h4 class="card-title">Cập nhật ảnh thương hiệu</h4>
			<form method="post" asp-action="Upload" asp-controller="Logo" enctype="multipart/form-data">
				<div class="input-group mb-3">
					<div class="input-group-prepend">
						<span class="input-group-text">Cập nhật</span>
					</div>
					<div class="custom-file">
						<input type="file" class="custom-file-input" name="logo">
						<label class="custom-file-label" for="inputGroupFile01">Chọn tệp tin</label>
					</div>
				</div>
				<button type="submit" class="btn btn-block btn-rounded btn-success">CẬP NHẬT</button>
				@Html.Raw(ViewBag.notification)
			</form>
		</div>
	</div>
	<!-- ============================================================== -->
	<!-- End PAge Content -->
	<!-- ============================================================== -->
	<!-- ============================================================== -->
	<!-- Right sidebar -->
	<!-- ============================================================== -->
	<!-- .right-sidebar -->
	<!-- ============================================================== -->
	<!-- End Right sidebar -->
	<!-- ============================================================== -->
</div>
<!-- ============================================================== -->
<!-- End Container fluid  -->
<!-- ============================================================== -->