Models/AboutUs.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MitechCenter.vn.Models
{
    public class AboutUs
    {
        [Key]
        public int auId { get; set; }
        public string auTitle { get; set; }
        public string auContent { get; set; }
        public int uId { get; set; }
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        [DefaultValue(false)]
        public bool isServices { get; set; }

        public DateTime? createAt { get; set; } = DateTime.Now;

        public DateTime? updateAt { get; set; } = DateTime.Now;

        [ForeignKey("uId")]
        public virtual User User { get; set; }

        public void DeepCopy(AboutUs about)
        {
            this.auId = about.auId;
            this.auTitle = about.auTitle;
            this.auContent = about.auContent;
            this.uId = about.uId;
            this.createAt = about.createAt;
            this.updateAt = DateTime.Now;
        }
    }
}

Components/OurServicesViewComponent.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MitechCenter.vn.Models;
using MitechCenter.vn.Models.DataManager;
using MitechCenter.vn.Models.Repository;

namespace MitechCenter.vn.Components
{
    public class OurServicesViewComponent : ViewComponent
    {
        public OurServicesViewComponent()
        {
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

Controllers/AboutUsController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MitechCenter.vn.Models;
using MitechCenter.vn.Models.DataManager;
using MitechCenter.vn.Models.Repository;

namespace MitechCenter.vn.Controllers
{
    public class AboutUsController : Controller
    {
        public AboutUsController()
        {
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/AboutUs/Index.cshtml
@{
    Layout = "~/Views/Shared/_MetaLayout.cshtml";
    ViewData["Title"] = "ABOUT US";
}
<!-- breadcrumb start-->
<section class="breadcrumb breadcrumb_bg" style="background: url('./img/tt1.jpg');background-position: center;background-repeat: no-repeat;background-size: cover;">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb_iner text-center">
                    <div class="breadcrumb_iner_item">
                        <h2>GIỚI THIỆU VỀ CHÚNG TÔI</h2>
                        <p>Trang chủ<span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- breadcrumb start-->
<!-- About us part start-->
<section class="learning_part" style="padding-top: 100px;padding-bottom: 50px;">
    <div class="container">
        <div class="row align-items-sm-center align-items-lg-stretch mt-5">
            <div class="col-md-7 col-lg-7">
                <div class="learning_img">
                    <img src="img/logo-mitech.png" alt="">
                </div>
            </div>
            <div class="col-md-5 col-lg-5">
                <div class="learning_member_text">
                    <h5>Đôi điều về Mitech</h5>
                    <h2>
                        Lịch sử hình thành
                    </h2>
                    <p>
                        Trung tâm Công nghệ thông tin và Ngoại ngữ, Trường Đại học Thông tin liên lạc được thành lập theo Quyết định số 988/QĐ-BQP ngày 28/3/2015 của Bộ trưởng Bộ Quốc phòng. Là tổ chức khoa học công nghệ công lập, Trung tâm có tài khoản và con dấu riêng, hoạt động theo cơ chế tự chủ về tài chính, hạch toán độc lập, được phép mở rộng hợp tác với các đối tác trong và ngoài nước.
                    </p>
                </div>
            </div>
        </div>
        <div class="learning_member_text" style="margin-top: 100px;">
            <h2>
                Chức năng
            </h2>
            <p style="color: ;">
                Trung tâm có chức năng đào tạo, bồi dưỡng nguồn nhân lực chất lượng cao về lĩnh vực CNTT cho Quân đội, đáp ứng nhu cầu quốc phòng, an ninh và công nghiệp hóa, hiện đại hóa đất nước; nghiên cứu phát triển các phần mềm cho Quân đội; phát triển, gia công phần mềm, cung cấp dịch vụ CNTT cho thị trường trong nước và quốc tế. Trước mắt, Trung tâm tập trung thực hiện chức năng đào tạo, bồi dưỡng nguồn nhân lực CNTT và ngoại ngữ cho Quân đội và xã hội; thí điểm mô hình đào tạo – nghiên cứu và cung cấp dịch vụ.
            </p>
        </div>

        <div class="learning_member_text" style="margin-top: 100px;">
            <h2>
                Cơ cấu - Tổ chức
            </h2>
            <p style="color: ;">
                Tổ chức của Trung tâm gồm: Ban Giám đốc, Ban Đào tạo và hợp tác quốc tế, Ban Nghiên cứu phát triển và chuyển giao công nghệ, Ban hành chính tổng hợp và đội ngũ giảng viên. Ngoài ra, Trung tâm còn có 02 chuyên gia Ấn Độ (01 chuyên gia về CNTT, 01 chuyên gia về KTVT) đến làm việc theo Biên bản ghi nhớ giữa hai nước.
                Hạ tầng, cơ sở vật chất hiện nay của Trung tâm được đầu tư xây dựng tương đối hiện đại, với các phòng chức năng: Khu văn phòng, phòng họp và tiếp khách, 03 phòng học ngoại ngữ, 04 phòng học CNTT, 01 phòng nghiên cứu thiết kế phần cứng; 01 hội trường 50 chỗ và hệ thống mạng tốc độ cao đủ điều kiện tổ chức các khóa đào tạo quản trị mạng, an toàn thông tin, lập trình ứng dụng và tiếng Anh giao tiếp.
            </p>
        </div>

        <div class="learning_member_text" style="margin-top: 100px;">
            <h2>
                Tình hình phát triển
            </h2>
            <p style="color: ;">
                Trung tâm đã được Bộ KH&CN cấp Giấy chứng nhận đăng ký hoạt động KHCN; Bộ Quốc phòng cho phép và Sở Kế hoạch đầu tư Khánh Hòa cấp Giấy chứng nhận đăng ký kinh doanh trong lĩnh vực CNTT và ĐTVT; Bộ GD&ĐT cho phép đào tạo tiếng Anh và CNTT.
                Trung tâm hiện là đối tác của Học viện Cisco Hoa Kỳ, tổ chức ICDL Châu Á, Tập đoàn Tech Mahindra Ấn Độ, Trung tâm đào tạo VITEC/ Khu CNC Hòa Lạc, Khu phần mềm Quang Trung/ Tp.HCM, IIG Việt Nam và nhiều cơ sở đào tạo, nghiên cứu khoa học, doanh nghiệp trong nước và quốc tế.
            </p>
        </div>

        <div class="learning_member_text" style="margin-top: 100px;">
            <h2>
                Phương hướng trong tương lai
            </h2>
            <p style="color: ;">
                Hiện nay, Trung tâm đang tiếp tục tổ chức các khóa đào tạo, bồi dưỡng nguồn nhân lựa CNTT và tiếng Anh cho cán bộ, nhân viên, sinh viên các đơn vị, nhà trường trong quân đội và nhu cầu của xã hội. Đồng thời phối hợp với các cơ quan chức năng và các đơn vị tư vấn nghiên cứu xây dựng Dự án đầu tư Trung tâm CNTT và ngoại ngữ giai đoạn 2 theo mô hình Khu công viên phần mềm để phát triển chuỗi liên kết nghiên cứu – ươm tạo – ứng dụng – sản xuất trong lĩnh vực CNTT.
                Dự án sẽ được triển khai tại số 75, Đường 2/4, phường Vĩnh Hòa, thành phố Nha Trang, tỉnh Khánh Hòa, trên khu đất khoảng 30.000 m2 gồm các phân khu chức năng: Phân khu văn phòng, trụ sở làm việc; phân khu đào tạo, tư vấn; phân khu nghiên cứu – phát triển; phân khu trưng bày, triển lãm, giới thiệu sản phẩm và truyền thông; phân khu công trình hạ tầng kỹ thuật đầu mối; phân khu sinh thái – dịch vụ dân sinh và hệ thống hạ tầng kỹ thuật đồng bộ. Khi hoàn thành xây dựng và đi vào hoạt động, công viên sẽ thực sự trở thành một trung tâm đào tạo, nghiên cứu và phát triển CNTT của Quân đội mang tầm cỡ quốc gia và quốc tế.
            </p>
        </div>
    </div>
</section>
<!-- About us part end-->

@{
    @await Component.InvokeAsync("OurServices");
}

<!-- Maps -->
<div class="d-none d-sm-block">
    <div id="map" style="height: 480px;"></div>

</div>
<!-- End Maps -->
@section styles {
    <style>
        .text-line {
            overflow: hidden;
            text-overflow: ellipsis;
            display: -webkit-box;
            -webkit-line-clamp: 2; /* number of lines to show */
            -webkit-box-orient: vertical;
        }

        .learning_part p {
            color: #142e60;
            font-size: 16px;
        }
    </style>
}

@section scripts {
    <script>
        function initMap() {
            var uluru = { lat: -25.363, lng: 131.044 };
            var grayStyles = [
                {
                    featureType: "all",
                    stylers: [
                        { saturation: -90 },
                        { lightness: 50 }
                    ]
                },
                { elementType: 'labels.text.fill', stylers: [{ color: '#ccdee9' }] }
            ];
            var map = new google.maps.Map(document.getElementById('map'), {
                center: { lat: -31.197, lng: 150.744 },
                zoom: 9,
                styles: grayStyles,
                scrollwheel: false
            });
        }

    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>
}